name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Stop Existing App
        run: |
          pkill -f app.py || true

      - name: Run Flask App
        run: |
          nohup python3 app.py > app.log 2>&1 &