name: Flask CI/CD Pipeline
on:
  workflow_run:
    workflows: ["CodeQL Analysis"]   # must match name: in codeql.yaml exactly
    types:
      - completed 

jobs:          
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stop Existing App
        run: |
          pm2 delete flask-app || true

      - name: Run Flask App
        run: |
          pm2 start app.py --name flask-app --interpreter venv/bin/python
          pm2 save
